# -*- coding: utf-8 -*-
"""eylul_cakmak_MIDTERM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XWHnlb5-RgahrMY-UZcUxzAy-VpgmSwa

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on Drive.
ex: atay_ilgun_MIDTERM.ipynb

**Describe what ML is in 50 words.**

Machine Learning is an idea that systems can learn from data, identify patterns and make decisions with minimal human intervention or without. From that definition I think we can describe human brain exactly like that too. Because when I think of the question “Can Machines Make Art?” then my answer do that question is always “Yes.”. If you give it enough data for it; art history, memories, dreams, images, videos.. you name it.. Then it’s not really different then our brain and our creativity. We see and hear things, we dream, we research, we get inspired. Why machine can’t do that? We are learning from data as well, our ideas are not fully ours after all. Also our decisions are made by some external factors as well even we insist that our decisions are fully ours, it’s not.

**Give 3 examples of ML in practical use in todays world - also, meditate on how it is being utilised as well.**

1- Chatbots 2- Spotify Discover Weekly 3- Amazon Echo or Google Home 4- Traffic Predictions 5- Facebook"People You May Know"

**In ML terminology what is an 'example', 'feature', 'label' and 'feature vector'?**

* An example is a particular instance of data. It has two categories: unlabeled and labeled. 
*   Feature is the number of features that can be used to describe items in a quantitative manner, the input.
*   Label is the final choice, the output.
* Feature vector is an n-dimensional vector of numerical features that represent some
object.

**In 100 words meditate on how future advancements on AI could affect your work practice as a communication designer.**

I want to be a service designer and when designing services probably we will be using artificial intelligence a lot. Because the services which AI involved, it is easier for the user. Creating an artificial intelligence is about understanding human needs because AI is for people, AI is here for helping us. How can it help us without understanding our needs and motivations? Designing services and using artificial intelligence with that service is the great combination. It will be a necessary tool/ knowledge for me to use in my future field and I am sure creating services with AI is going to be fun.

**Try to describe how you learn in algorithmic terms.**

My brain as a human, receives data from lots of places in a day and it has the information in its short-term memory. It has lots of strings, lists and so on. The problem is our brains get all the information regardless of whether it is true or not. But a computer can detect the wrong information and can reject it at the first place. Our brain is more complicated than how computer works. That is why I am receiving all the data and sometimes having the unnecessary data like Atilla Taş's song lyrics instead of information that I learnt in my ML course. Also, the other thing worth to mention is about how I learn is, getting into a "loop". Repeating the same thing over and over again makes learning and memorizing easier for my brain.

Create a python dictionary for your name surname and year of birth.
"""

a_dict = {'name': 'eylul', 'surname': 'cakmak', "year": '1997'}

a_dict1.keys()

a_dict1.values()

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

a = a_dict1['name']

if a[0] == a:
  print('my initial is a!')

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

my_surname = a_dict1['surname']

if len(my_surname) % 3 == 0:
  print('it is divisible')
else:
  print('not divisible')

"""Change your year of birth to 2678."""

a_dict1['year of birth'] = 2678

print(a_dict1)

"""**Create a loop that goes through 20 to 40 and prints out the numbers that are divisble by 5**."""

list_1 = range(20,40)

for everynumber in list_1:
   if everynumber % 5 == 0:
    print(everynumber)

"""**Check the PDF on the Drive and calculate the neurons. Put all neurons and weights in python and do the calculation with them.**"""

n1_1 = 0.87
w1 = 0.06

n1_2 = 0.12
w2 = 0.12

n1_3 = 0.62
w3 = 0.47

print((n1_1*w1) + (n1_2*w2) + (n1_3*w3))

"""Using the code here:
https://github.com/anishathalye/neural-style
create a ***style transfer*** image.

Upload it along with this file.

You might need a file while doing this, it also is on the Drive!
"""